### ISSUE TITLE
Docker Compose configuration prevents tagged image updates

### ISSUE THREAD

**Issue by cdubz** [cdubz/babybuddy#106]
~~A Docker user brought this up to me over email. Apparently the way Docker is currently setup relies on working from a local copy of Baby Buddy’s code (i.e. a `git clone`) and the Docker Hub image being built doesn’t have the code so can’t work independently.~~

I am not familiar with Docker generally so I’ll need to figure out how to resolve this and/or would love help!

**Comment by DarkMagic** [comment]
The docker image doesn't need to have source code in there.
Inside docker container, there're **/app** folder which could be mapped to host's volume. User can edit/modify content of host's directory, it will be reflect automatically to inside container.

**Comment by cdubz** [comment]
I have tested this a bit and I think I have at least some small grasp on what is happening here. PR #81 introduced [this change](https://github.com/cdubz/babybuddy/pull/81/files#diff-4e5e90c6228fd48698d074241c2ba760R20) to the `docker-compose.yml` file --

https://github.com/cdubz/babybuddy/blob/a0a6c88a19ecd11e5a1221dd785e91792eb4b737/docker-compose.yml#L20-L21

Marking the `app` volume as `rw` makes it persistent, so updating the image does not have any affect on the code.

E.g. if someone is using a tagged image, `cdubzzz/babybuddy:version-1.2.4` and attempts to update that to `cdubzzz/babybuddy:version-1.3.0`, the application code will not get updated because the volume won't be replaced. This use case is resolved by removing the above referenced lines from the `docker-compose.yml` file.

However, I am unsure if making this change breaks some other use case. I would be interested to hear from @paulcalabro (or anyone else with Docker experience!) on this before making any change.

In the mean time, people with the tagged version use case (@LostSoulfly?) can get updated by removing the `volumes` data from the `app` service, updating the tag, and then restarting the services, assuming no intentional changes have been made to the application code in place (e.g. settings files?).

**Comment by LostSoulfly** [comment]
Thanks for the mention. I'm not currently using a tagged release version-
![image](https://user-images.githubusercontent.com/9120519/73611662-0181cb00-45b2-11ea-8f1e-921d4bd8a031.png)

I will try a force pull of the container and see what happens shortly.

**Comment by cdubz** [comment]
Yeah I guess actually the tagging part isn’t relevant here. Just the `rw` mount of `/app`. I think this make sense for development use or users who want to customize the code. But not for people who just want to use the app as is. I’m considering getting rid of the repo supplied compose file and rebuilding it as an example with more detailed documentation.

**Comment by LostSoulfly** [comment]
I did a pull and rebuild, no update. Looks like it's still loading from the docker volume.

What ended up allowing the update to take was removing the app volume only and re-pulling it, then performing the database migration.

```
docker-compose down
docker volume rm baby_app
docker-compose up -d
docker-compose exec app python manage.py migrate
```

**Comment by cdubz** [comment]
Yep that follows with what I have heard from other Docker users. I’m going to turn the repo provided compose file in to an example and provide more detailed documentation on different ways to use it.

I’ll also look in to an auto migrate command. I think that would make sense.

**Comment by cdubz** [comment]
The Docker deployment documentation has been updated.

I didn't end up adding migration automation because there doesn't seem to be a "clean" way to do it and I lean towards not wanting to automatically change database data during Docker operations that do not specifically request it.

Thanks to everyone who helped sort this out! I now understand Docker *slightly* more (:
