### ISSUE TITLE
Use docker-compose's environment instead of docker.env file

### ISSUE THREAD

**Issue by DarkMagic** [cdubz/babybuddy#110]
I think both **docker-compose.example.yml** and **docker.env.example** are using for set example purpose. So it should be combined to 1 file instead of 2, some advantages:
- Single place to maintain.
- Reduce complexity for new users.

To do that, the content of **docker-compose.example.yml** could have one part for environment like below:
```
...
  app:
    container_name: babybuddy-app
    image: cdubzzz/babybuddy
    environment:
      - ALLOWED_HOSTS=*
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=babybuddy.settings.docker
      - SECRET_KEY=some-secret-characters
    command: gunicorn -c /app/gunicorn.py babybuddy.wsgi
...
```

What is your opinion @cdubz ?

**Comment by cdubz** [comment]
That makes sense. Would also simplify the Docker install instructions. I like this idea.

**Comment by cdubz** [comment]
This change has been made. Thanks for the suggestion!
