### ISSUE TITLE
Add photo field to Child model

### ISSUE THREAD

**Issue by cdubz** [cdubz/babybuddy#13]
Optional field - would be fun for parents and useful for multi-child instances (especially with a cleaned up dashboard).

**Comment by cdubz** [comment]
It looks like [django-storages](https://django-storages.readthedocs.io) would be needed to support external storage services for media files in order to maintain easy deployment to services like Heroku.

Some other packages to consider for working with images:

- [django-imagekit](http://django-imagekit.readthedocs.io/)
- [easy-thumbnails](http://easy-thumbnails.readthedocs.io/)
- [django-avatar](http://django-avatar.readthedocs.io/)

I don't have any experience with this or the remote media files storage hookups, so will probably sit on this idea for a bit.

**Comment by overshard** [comment]
Optional field added in #19

**Comment by cdubz** [comment]
Also added the picture to the multi-child dashboard in 092d72490649124c0276a802227ac94f93108dd7. Easy thumbnail is sweet!

**Comment by cdubz** [comment]
Just did a test deploy to Heroku to verify that everything still works (except pictures) and it does. It would be nice if, even with the remote storage, we could run some sort of test to determine whether or not media storage is available and show/hide the Child picture field based on the result. Or maybe just throw a form error if that is easier.

Currently, at least on Heroku, it seems to think that the upload worked so you just end up with a broken image link wherever the picture is supposed to load.

**Comment by cdubz** [comment]
#20 merged. I may want to move `ALLOW_UPLOADS` to the `BABY_BUDDY` dict. I was thinking of putting all custom settings in there to keep things organized and documented.

**Comment by cdubz** [comment]
Closed by #33. Support for other cloud-based hosted can be handled in additional issues/PRs.
