### ISSUE TITLE
Docker installation

### ISSUE THREAD

**Issue by dunhamspider** [cdubz/babybuddy#21]
Not an issue, but a feature request:
Is there a possibility to add docker installation instructions?
I'm just starting to learn, and currently I'd like to reroute multiple webapps through a nginx reverse proxy.
The problem is nanobox seems to only like outputting on port 80.
With a more simple setup, and a docker image, one could output on localhost:anyport and route that to a subdomain using nginx

**Comment by cdubz** [comment]
Hah, @overshard and I were just talking about this yesterday after I finished documenting the painfully long “manual” install instructions (: I’ve been looking for an excuse to learn about Docker anyway, so I’ll start working on this next.

**Comment by cdubz** [comment]
Oops. Didn’t mean to close that. Fat finger.

**Comment by dunhamspider** [comment]
haha thank you very much.

**Comment by cdubz** [comment]
Made a little progress on this. I'm not quite ready to merge yet as I'm not 100% confident in the process. @dunhamspider (and maybe @overshard), could you poke around with the [`docker` branch](https://github.com/cdubz/babybuddy/tree/docker) and see how a build and deployment goes?

**Comment by dunhamspider** [comment]
having a bit of trouble convincing docker.env to actually work.
I use a IP, and the ALLOWED_HOSTS=['ip', 'localhost', '127.0.0.1']
and yet the server yells out Invalid HTTP_HOST header: 'ip:5002'. You may need to add 'ip' to ALLOWED_HOSTS.

I'll play around with it a bit more, I think I need to rebuild the image because it's not updating the .env file

**Comment by cdubz** [comment]
You shouldn’t need to rebuild after changes to the env file. I forgot to add documentation about `ALLOWED_HOSTS` - it should be a comma-separated list with no spaces. The settings file converts it to a list. So for you example:

`ALLOWED_HOSTS=ip,localhost,127.0.0.1`

**Comment by dunhamspider** [comment]
aaaa, thanks. P.S. the documentation says:
docker-composer up
it should be docker-compose up, and you can use -d to run it unmanaged

**Comment by dunhamspider** [comment]
It works now. Problem is, I don't think any credentials exist, and I can't seem to find a way to register

**Comment by cdubz** [comment]
Oh nice. Didn’t know about the `-d` flag. Does the set up generally seem to make sense to you, as someone who has used Docker elsewhere?

I’d like to find a way to roll the `collectstatic` and `migrate` commands in to the initial build process. I originally had them in `Dockerfike` but it required passing ARGs and even then links apparently aren’t available at build time so running `migrate`wasn’t possible.

**Comment by cdubz** [comment]
Re: credentials: `admin`/`admin` should work. It’s partof `migrate`

**Comment by dunhamspider** [comment]
works great :)
I cleaned up my images and tried to do docker-compose up directly, which caused the migrate phase to not occur. I'm sure you can script that into the yml, but I'm sorry I have very little knowledge on docker, I'm learning too

**Comment by cdubz** [comment]
Cool. It’s a start (:

Maybe I can chain those commands in the yml... It wouldn’t hurt to run them every time, I suppose. I just couldn’t figure a good way to have them run only once.

**Comment by dunhamspider** [comment]
Also, you can start the docker-compose up, and then run docker-compose exec instead of run:

docker-compose exec web python manage.py migrate
docker-compose exec web python manage.py collectstatic

P.S. I'm in GMT+2, and the django settings seem to be set to GMT-5? I think.
I tried to put it in docker.env, as TIME_ZONE, but I don't think it's parsed. Maybe worth looking into

**Comment by cdubz** [comment]
> you can start the docker-compose up, and then run docker-compose exec instead of run

Ah ok. I thought the way I was doing it was weird, hah.

> I tried to put it in docker.env, as TIME_ZONE, but I don't think it's parsed.

`TIME_ZONE` is not controlled in `docker.env`. I haven't quite decided how I want to handle other Django settings. The typical Django way would be to take a look at the [`base.py`](https://github.com/cdubz/babybuddy/blob/docker/babybuddy/settings/base.py) settings file and override anything there in your deployment's [`docker.py`](https://github.com/cdubz/babybuddy/blob/docker/babybuddy/settings/base.py) settings file. But this assumes general knowledge about Django, so maybe I can abstract that away a bit.

I was actually thinking of adding a general `.env` file and basically turning all the Django settings in it as environment variables so people could relatively easily make changes without knowing anything about Django. @overshard, I would appreciate your thoughts on this as well.

**Comment by cdubz** [comment]
Ok the Docker changes are merged in. Thanks, @dunhamspider for your help!

Will continue discussion re: using an `.env` file in #22.
