### ISSUE TITLE
Documentation on the API

### ISSUE THREAD

**Issue by xrd** [cdubz/babybuddy#28]
Is there documentation on using the API that appears in the routes? Is this a standard interaction if you know the routing framework for Django? My goal is to have a webhook hit the app and add data to the database. Is there a way to protect this other than IP whitelisting?

**Comment by cdubz** [comment]
Thanks for the prompt. I keep thinking about this and then forgetting it.

So the app uses the Django REST Framework plugin and should be fairly straight forward. If you run the development server you can access the full API Browser from the user menu and poke around.

I need to figure out how security works though and get some documentation in. I *believe* it uses the Django account for auth but I have no idea how.

I’ll work on this soon. Any support/observations are welcome if you do mess around with it.

**Comment by xrd** [comment]
I'm not a Python user generally. Can you point me to directions on how to run the app in development mode? Is that in the readme?

I'll poke around with curl and see if I can come up with some examples of how it works and add them to the thread.

**Comment by cdubz** [comment]
See [Development - Installation](https://github.com/cdubz/babybuddy#installation) for instructions.

After reading up on this bit, I don't think you'll get very far though. I believe I need to configure [Token Authentication](http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication) in order to allow requests outside of a regular app session authentication. I'll work on getting this and some documentation in place soon.

**Comment by xrd** [comment]
OK. My intention was to find a way to allow Google Home to communicate with the app. Since I'm not much of a python person, I hacked together a ruby version which you can find in a branch on my fork. If you are interested, I can share the DialogFlow project with you so you can understand how it works. Right now all that works is just adding feedings, but it will be simple enough to add the rest.

**Comment by cdubz** [comment]
Oops! Didn't mean to close that, hah.

I have made the necessary changes to use [token-based authentication](http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication) through DRF. Just need to add documentation and then I'll push it all up (after work in a few hours).

**Comment by xrd** [comment]
Cool. I'll check it out then. Also, my fork has nginx+ssl support which is necessary for Google Home if you want that for this project.

**Comment by cdubz** [comment]
Just pushed all the new API code and documentation. If you update an existing instance, you'll need to run the the `migrate` command again as some database changes were made.

Hop on gitter or open another issue if you have suggestions or trouble.

I'll take a look at your fork. It would be good to have instruction for SSL set up now, but I worry about things getting too complicated.
