### ISSUE TITLE
Improve dashboard mobile performance

### ISSUE THREAD

**Issue by cdubz** [cdubz/babybuddy#31]
We have been experiencing odd issues with the mobile view - often when re-opening the browser with the dashboard, or waking the phone with it already loaded, the dashboard seems to lock up and in my experience Firefox iOS will frequently crash. Chrome on iOS appears to have a similar, but slightly less severe issue (it can usually recover after a second or two).

I'm not sure yet if this is an iOS general, iOS 11, page visibility api, or other issue.

**Comment by overshard** [comment]
I recommend using the Page Visibility API to solve this issue: https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API

You will want to not run the dashboard update reload if the page isn't visible or in focus. I solved a similar issue in another app with this.

**Comment by cdubz** [comment]
The current version makes use of [visibilityjs](https://github.com/ai/visibilityjs), but I think maybe my implementation of it is not real clean. It's not even very much, and is all in [dashboard.js](https://github.com/cdubz/babybuddy/blob/master/dashboard/static_src/js/dashboard.js#L12). I think this is either a browser support issue or something weird about how I have done it. Either way, it's tough to track down because it's very inconsistent.

**Comment by cdubz** [comment]
Looks like replacing visibilityjs with an ``focus`` event listener (a5242595073ce00a55ef7726ceeb2b9ea9a5d20f) has made this much more stable. Closing for now.
