### ISSUE TITLE
Configurable units?

### ISSUE THREAD

**Issue by saghul** [cdubz/babybuddy#36]
Hi there! Love the work you've done here, I just started using it with my daughter!

I noticed the feeding units are hardcoded to ounces, any chance you could make it configurable for us metric folks? :-)

**Comment by cdubz** [comment]
Yeah, we're all over the place with units. I've generally just avoided using units at all (see weight), leaving it to the user to decide. The feeding amount field only shows "oz" in the list view (I think?). What I will likely do for now is just remove units where I see them.

Let me know what other things you run in to as you use it! My son is a little over six months now and we have pretty much settled in to our own habits of use, so new perspectives will help me identify improvements and additions we haven't thought of.

Congrats and good luck!

**Comment by cdubz** [comment]
911cde4f9563472ace1a906526aadead2910f924 makes the small change of removing the couple uses of "oz".
