### ISSUE TITLE
New logo for Babybuddy

### ISSUE THREAD

**Issue by reallinfo** [cdubz/babybuddy#38]
I wanted to contribute to Babybuddy. I designed a logo for it. If you like it, I'll send you files and pr. i hope you like it :)

is there anything you want ?

![babybuddy](https://user-images.githubusercontent.com/36298335/38771138-375a2e4a-4026-11e8-8002-0d216905e45f.jpg)

**Comment by cdubz** [comment]
Hey! This is very neat, I like where you are going with it. A couple of requests/thoughts -

- Do you think the baby could have a smile or happy-neutral sort of expression? I worry that it would ruin the "clock face" effect (which I love), but I would also like the logo to convey that BB can help make for a happier baby.
- I wonder also if the eyeballs could be in a more normal position? Something about going up in opposite directions is a little odd. Although, my son's eyes were like that sometimes in the early days (:
- Lastly, I wonder if it could go a different direction with the overall color of the logo? I think a non-skin tone color might be more appropriate. Baby Buddy does not have a particularly great color scheme, so I'm not quite sure what the best approach would be. Any thoughts? If you don't think that would work, I would focus on the two boxed-in white ones on the bottom row, which I think would fit Baby Buddy's dark theme at the right size and could have any number of secondary colors.

Thanks for your efforts. I took a look at some of your other PRs and you've done lots of cool stuff!

**Comment by reallinfo** [comment]
I made a few more designs for you :) Please take a look at these. If you have another opinion, you can tell me.

![1](https://user-images.githubusercontent.com/36298335/38778727-831399f2-40c6-11e8-9247-b3e7ce49db79.jpg)

**Comment by cdubz** [comment]
Nice. I'm liking the single color versions in the fifth column. One more variation idea -

Could the center of the clock hands be circular, with the hands a bit thinner and/or tapering (e.g. [more like this](http://ecx.images-amazon.com/images/I/61xdZ4xMH-L._SL1500_.jpg) but without the overlap at the center)?

**Comment by reallinfo** [comment]
Oh, okay. How is that?

![bb](https://user-images.githubusercontent.com/36298335/38784097-7d8bdebe-4115-11e8-9f5f-c774779a904b.jpg)

**Comment by cdubz** [comment]
Nice! I like it. Happy to accept a PR adding the blue variation to the repo (I think `babybuddy/static_src/logo` would make sense) and README. For asset files I'd love to have one with the background and an inverted version of just the logo in white with trans for the features.

Thanks very much for your contribution!

**Comment by reallinfo** [comment]
I am glad you like it :) I sent pr but If there is something you want to change in PR please tell me because, in addition I have added horizontal and vertical versions. 

https://github.com/cdubz/babybuddy/pull/39

Here are all the files;

https://drive.google.com/open?id=1UxqIdRHw677Zq90mjIkObJcnaqLRnUEX

**Comment by cdubz** [comment]
Closed by #39. Thanks again, @reallinfo!
