### ISSUE TITLE
configure nginx

### ISSUE THREAD

**Issue by novski** [cdubz/babybuddy#47]
I can't reach my babybuddy app. And im not sure how to solve. 
I installed the manual way as in the readme.md and as we discoussed for a Raspberry pi.
My hostname is set to babybuddy in the `sudo raspi-config` panel. Now i can reach with URL:"babybuddy.local" the default "welcome to nginx" site if i set the `/etc/nginx/sites-enabled/babybuddy` file to:
```
upstream babybuddy {
     server unix:///var/run/uwsgi/app/babybuddy/socket;
 }

 server {
     listen 80;
     server_name xy.local;

     location / {
         uwsgi_pass babybuddy;
         include uwsgi_params;
     }
 }
```
 but get a `bad request (400)` if i set it to:
```
upstream babybuddy {
     server unix:///var/run/uwsgi/app/babybuddy/socket;
 }

 server {
     listen 80;
     server_name babybuddy.local;

     location / {
         uwsgi_pass babybuddy;
         include uwsgi_params;
     }
 }
```
i read this tutorial: [https://uwsgi-docs.readthedocs.io/en/latest/tutorials/Django_and_nginx.html](https://uwsgi-docs.readthedocs.io/en/latest/tutorials/Django_and_nginx.html)
saddly the log in (/var/log/nginx/error.log) is empty and a second file in that folder named error.log.1 has only this single line in it: 
```
pi@babybuddy:/var/log/nginx $ sudo cat /var/log/nginx/error.log.1
2018/05/07 23:33:17 [notice] 5234#5234: signal process started 
```
my user `pi` is in the group `www-data`.
my /etc/uwsgi/apps-available/babybuddy.ini file is configured like this:

```
[uwsgi]
 plugins = python3
 project = babybuddy
 base_dir = /var/www/babybuddy

 virtualenv = /home/pi/.local/share/virtualenvs/public-BuvyXxxq
 chdir = %(base_dir)/public
 module =  %(project).wsgi:application
 env = DJANGO_SETTINGS_MODULE=%(project).settings.production
 master = True
 vacuum = True
```
because pipenv --venv spits out this:
```
pi@babybuddy:/var/www/babybuddy/public $ pipenv --venv
/home/pi/.local/share/virtualenvs/public-BuvyXxxq
```
What can i test further to locate the failure?

**Comment by cdubz** [comment]
The config all looks good to me. Perhaps you found more issue with the README (:

I will test this out later today and let you know what I find.

**Comment by cdubz** [comment]
@novski -- you need add `babybuddy.local` to the `ALLOWED_HOSTS` array in `/var/www/babybuddy/public/babybuddy/settings/production.py`. E.g. `ALLOWED_HOSTS = ['babybuddy.local']`. After you change that, restart uWSGI and you should be good to go.

I'll think about how to reformat the steps to highlight. Right now it's a bit of a chicken-and-egg scenario.

**Comment by novski** [comment]
Thanks this worked now. How about a wiki site? A page per operatingsystem wold do the job maybe?
