### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by djmwj** [cdubz/babybuddy#50]
I see there is support to change the default time zone for the host. Good practice is to always have the host on UTC time, but it does not appear that the app currently uses the browsers time zone for caclulating the current datetime, it simply uses the servers time. Is this accurate? 

I am not very strong in django, but i think this needs to be added to allow the browser to use its own time zone. J ust struggling with where:

```
from django.utils.timezone import activate
activate(settings.TIME_ZONE)
```

Source: [https://docs.djangoproject.com/en/2.0/topics/i18n/timezones/#default-current-time-zone](url)

**Comment by cdubz** [comment]
Currently all dates are stored in UTC but formatted based on the server time (which is all Django knows). I imagine there is some path to have the client set this but it’s not something I have seen in practice (I am also pretty new to Django, though).

We have been using BB for just about nine months and we actually changed time zones about six months in. The only way I could think to address that would be to store the TZ with every datetime entry, and that would allow for an easier path to setting the TZ from the client as well, I think.

I haven’t had the time to dig in to any of this but I’d be happy to look at any info you or anyone else can dig up on it.

**Comment by cdubz** [comment]
Capturing this here as a related discussion -- https://codeblog.jonskeet.uk/2019/03/27/storing-utc-is-not-a-silver-bullet/

**Comment by r0n0c** [comment]
Related. I used the manual setup. Ngnix/sqlite/Ubuntu 1804

Feedings fields are populating with current server time 'America/Chicago'. However the dashboard is saying everything is 5 hours off. I am guessing this is because things are stored in UTC and calculated from that.

**Comment by cdubz** [comment]
Yes, I have noticed that to. I *think* this is because the UI relies on the framework to set the TZ on the server side. So if you set the TZ correctly there (see the [`TIME_ZONE` env var ](https://github.com/cdubz/babybuddy#time_zone) for an example of how to this), everything should work out correctly.

At any rate, this is certainly confusing and needs to be fixed. It is the next thing I intend to work on, but my little one is now dealing with daycare and separation anxiety. Finding myself missing the immobile, sleep-filled days (:

**Comment by r0n0c** [comment]
Thank you that was the bit I needed. I had set it in several places, but not there. I have setup several lamp services for local stuff. This is my first with python virtual environments, ngnix, uwsgi, and django. It is a lot of black magic buggery going on at this point for me. Reading is needed. 

I feel ya on the missing the potato baby. I have a 2 yr old, and we brought home our identical girls from the NICU this weekend. They are way easier to handle than their older brother. Thank you for you fast reply.

**Comment by cdubz** [comment]
Glad that helped. And precisely the type of thing no one wants to futz with while juggling three kiddos (: Congrats on the twins and glad they made it safely out of NICU! Hope mama is doing OK as well.

**Comment by cdubz** [comment]
Today I also noticed that the timezone in the frontend is handled differently in different forms too, which is bad. E.g. the [Start Timer](http://demo.baby-buddy.net/timer/add/) autofills the date and time with the timezone from the application timezone while all the other add entry forms (e.g. [Add Diaper Change](http://demo.baby-buddy.net/changes/add/)) use the local timezone from the browser.
