### ISSUE TITLE
Feature Reqest: Temperature

### ISSUE THREAD

**Issue by novski** [cdubz/babybuddy#53]
its sometimes when my litle is sick good to keep temperature in sight. In the dropdown of Children there is a Wheigt Dataset. I see that Feature similar to that. 
What do you think? 
Would you help me with question answering if i wold implement that myself?

**Comment by cdubz** [comment]
Happy to provide support if you want to build this out and PR (: Gitter may be best for back-and-forth. If you look at how the Weight model is implemented, a Temperature model should be fairly similar.

**Comment by r0n0c** [comment]
Is there a way to use the backend admin side of things to just add another element to track?

**Comment by cdubz** [comment]
Not from the UI -- you would need to implement the model in code. Are you also interested in tracking temperature? Or something else?

**Comment by r0n0c** [comment]
Temp and vitamin/medicines for the day

**Comment by cdubz** [comment]
Well, temperature would be easy enough to add in the same way that weight is used (simple numerical value without any units in the UI and basic integration).

But, I could see vitamin/medicine tracking being rather complicated. Could you make a case for that in another ticket, with more details on how'd you would see it working? In the meantime, notes may be enough for keeping a running log you can at least refer back to over time.

**Comment by cdubz** [comment]
Temperature support added in 4397d4a4065a17a476cb4bcc2396c7346e0ccd24. Closing this -- open a new issue if you have any problems with it!
