### ISSUE TITLE
Manual Installation on ARM7: ImportError: Missing required dependencies ['numpy']

### ISSUE THREAD

**Issue by novski** [cdubz/babybuddy#55]
I get this error when gulp migrate is executed on a Raspberry Pi 3B+ Manual Server Installation
```
    import pandas as pd
  File "/home/pi/.local/share/virtualenvs/public-BuvyXxxq/lib/python3.5/site-packages/pandas/__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']
[09:27:05] 'migrate' errored after 6.61 s
```
I now tried to checkout older commits and installed as i had done in May2018. All builds back to the one i worked on myself break with missing dependency numpy. By then it did not error, so it does not seam to be a self initiated error to me. 
More like a package that has changed for arm devices. 

Can somebody confirm that on a same Raspberry Pi B+ maybe?

**Comment by cdubz** [comment]
I don’t have a B+ but I’ll give it another try on my B when I get a chance.

**Comment by killua99** [comment]
Hi I'm having an issue, not directly with manual installation but with Docker on a ARM 64 board, to be more accurate Pine64 with Arch Linux on it.

Seems like, panda is missing, and a couple of gcc to compile.

This is the error. https://kopy.io/y4MqQ

The traceback is huge, let me know if you want it as well.

**Comment by cdubz** [comment]
Closing this as we haven't heard anything back. @novski feel free to reopen if you get any new info. I still don't have a B+ to test with.
