### ISSUE TITLE
Safari pinned iOS App links to Home / Permission denied

### ISSUE THREAD

**Issue by novski** [cdubz/babybuddy#57]
Visiting my Babybuddy with safari on iOS and pinning it to the Homescreen of my iPhone works. Taping on that nice babybudy icon on my Homescreen leads me to a page with a breadcrumb: Home / Permissions Denied. Switching back to Safari im still loged in. In menu there is a AnnonymousUser loged in that if i press logout leads to a switch over to Safari where i land on the login page.
Did someome ever noticed that?

**Comment by HorizonXP** [comment]
I did. I'm going to try to investigate and fix this now.
