### ISSUE TITLE
Module 'encodings' not found

### ISSUE THREAD

**Issue by SwapFaceL** [cdubz/babybuddy#67]
Hi,

I followed the instructions to install on Ubuntu Server 18.04.
During the installation not errors were display.

However, I could not start the app. The uwsgi-app-log, shows the following error:
`Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'`

Is it a bug or just my system? Any idea how to fix this?
Thanks in advance :)

**Comment by cdubz** [comment]
I think this can often be a Python version mismatch or issue with the venv. Assuming you followed the manual install instructions (correct me if I'm wrong), please post the contents of your `/etc/uwsgi/apps-available/babybuddy.ini` from step 10 and `/etc/nginx/sites-available/babybuddy` file from step 12.

**Comment by r0n0c** [comment]
Do you have the default site enabled on ngnix?

**Comment by SwapFaceL** [comment]
Basically I used the defaults. Just adjusted the env path and other paths to my systems settings.

**Comment by SwapFaceL** [comment]
And thanks a lot for the fast replies!

**Comment by cdubz** [comment]
Not much else we can do to troubleshoot from this info. @SwapFaceL please re-open and provide some more details if you need additional help.
