### ISSUE TITLE
feature request: Feeding daily input

### ISSUE THREAD

**Issue by r0n0c** [cdubz/babybuddy#68]
We have preemies and our nutritionist needs daily total input. It would be nice to have a dashboard item showing feedings daily totals.

**Comment by cdubz** [comment]
Should be pretty straight forward and seems like a good one to have. I'll see what I can do.

**Comment by cdubz** [comment]
There is now a "Feeding Amounts" report on `master`. Give it a try and let me know if you have any issues.

**Comment by r0n0c** [comment]
I see it, but it is showing the amount of a single feeding. not the totals for the day.

let me know if anything would be helpful to show.
![Capture](https://user-images.githubusercontent.com/4976056/58590881-b812fc00-822a-11e9-9779-4fc7ed32f1de.PNG)
 we log feeds in ml.

**Comment by cdubz** [comment]
I got caught up with a weird Plotly issue and didn't actually finish the functionality (: This should be fixed now. It also wasn't adjusted for timezone.

**Comment by r0n0c** [comment]
Works for me now. Thank you!!
