### ISSUE TITLE
Enhancement: "Fortified breast milk" Option

### ISSUE THREAD

**Issue by r0n0c** [cdubz/babybuddy#71]
Our girls are drinking breast milk fortified with formula to up the caloric count. We have just been using the "Breast milk" option, but now one twin has been on straight breast milk (to try and help with reflux issues) and I'd like to be consistent.

**Comment by cdubz** [comment]
Shouldn't be a problem. I'll sneak this in some time soon.

**Comment by cdubz** [comment]
Added and included in the [v1.2.3 release](https://github.com/cdubz/babybuddy/releases/tag/v1.2.3).
