### ISSUE TITLE
FR/Question: active timers on home dashboard

### ISSUE THREAD

**Issue by burkemw3** [cdubz/babybuddy#73]
What do you think about putting active timers on the home dashboard (`/dashboard/`) similar to how active timers are available on a child's dashboard (`/children/baby-name/dashboard/`)?

I think it'd be useful to get to active timers faster, especially when tracking multiple children.

**Comment by cdubz** [comment]
Definitely a good idea. I’ve only ever dealt with one kid at a time so it’s useful to get insight from folks with more (: I’ll work on adding something.
