### ISSUE TITLE
graph.da32e0532ca2.js.gz is empty

### ISSUE THREAD

**Issue by janLo** [cdubz/babybuddy#75]
The static file is empty which causes the plotly graphs not being shown.

I use the docker image. If I call `python manage.py collectstatic` the file is not regenerated (also not after a `--clear`.

**Comment by cdubz** [comment]
Hm, I don't think you should need to run `collectstatic` (unless you are modifying something in the styles?). Or maybe I have outdated documentation somewhere? Could you give a step-by-step description of how you get the issue?

**Comment by janLo** [comment]
The file https://github.com/cdubz/babybuddy/blob/master/static/babybuddy/js/graph.da32e0532ca2.js.gz is empty. Also in the docker image. That's why the plots don't work. I tried to regenerate it on container startup but it won't get generated.

**Comment by cdubz** [comment]
Derp. Thanks. Didn't pick that up in the demo because for some reason it doesn't use the collected assets. Need to look at why that is...

Anyway, I'll check this out soon. The other assets appear to have built fine so I'm guessing some new issue with Plot.ly... argh.

**Comment by cdubz** [comment]
Looks to be resolved (got the production assets loading in the demo). New Docker build is underway...
