### ISSUE TITLE
API questions

### ISSUE THREAD

**Issue by cdubz** [cdubz/babybuddy#76]
Also my API game is a little weak, and I'd like to know if there is a way to accomplish my second thought via the API... I plan to create a raspberry pi device with buttons so we can just push a button and have it log the info into the app so we don't have to fumble with/find our phones, just push the button and be done. I'm planning to have a button for diaper changes, one to start feeding and one to stop feeding, but I'm not sure the best way to accomplish this with the API so any guidance would be appreciated there.

Thank you for making such an awesome app!

_Originally posted by @TheEagle13 in https://github.com/cdubz/babybuddy/issues/32#issuecomment-511213110_

**Comment by TheEagle13** [comment]
Sorry, guess I should have separated that into a separate issue...

**Comment by cdubz** [comment]
No worries.

The trouble with the button approach is that you are limited to a single input (the button!), while all of Baby Buddy's models have multiple inputs. E.g. for a breast feeding entry this is:

1. Child
1. Start
1. Stop
1. Type
1. Method
1. Amount

Of those, only Amount is optional, so I'm not sure how best to work that our with a single button click. The Child you can hardcore (assuming one!), and start and stop times could be tracked by any initial and second button press. But then how would one capture type and method?

The rest you could potentially get away with. For diaper changes you would need one button for each type (wet and solid), assuming you don't care about solid color (which is optional). Then sleep and tummy time could each be one button that would handle two presses -- one to start and one to stop.

From there the API work should be fairly straightforward. It is (I think!) fairly well documented in the [API documentation section](https://github.com/cdubz/babybuddy#api).

**Comment by TheEagle13** [comment]
I'll have to see if I can figure out the start/stop commands for sleep/tummy time API. APIs have never been easy for me (for some reason, even with how stupid simple they are). I think It's because every system seems to treat their APIs differently.

For the Breast feeding, We will only have one child, and initially when we would mostly use the button instead of the web gui, the Type would be static. So I guess the hard part would be to figure out how to tell it to alternate from the last breast and handle start/stop commands. Any Ideas, or does breastfeeding seem too difficult to implement into a hardware button?

Thanks for your help

**Comment by cdubz** [comment]
The API just accepts instances of the various models. So you don't need to worry about starting or stopping anything -- just send a payload with a start and stop time included. E.g. a `POST` payload for a new breast feeding entry may look like this --

```json
{
    "child": 1,
    "start": "2019-07-08T20:27:30.079879Z",
    "end": "2019-07-08T20:38:30.079879Z",
    "duration": "00:11:00",
    "type": "breast milk",
    "method": "left breast",
}
```

So the logic for determining the start and end time would need to happen on your controller for the button (the Pi or whatever else).

If you ignore the other options for breast feedings, you could just have two buttons -- one for the left breast and one for the right (:

**Comment by meichthys** [comment]
@TheEagle13 Have you implemented some type of physical button? I had the same idea and came across your comments. I'd be interested in hearing/seeing your method if you've implemented something! I actually use [HomeAssistant](https://www.home-assistant.io/), so i was considering making some kind of integration that uses the API to add a button on the the HomeAssistant dashboard.

**Comment by TheEagle13** [comment]
I never got around to it... Prepping for the baby led to not enough time, then baby led to not enough sleep, then I didn't find much of a need for it anymore.
