### ISSUE TITLE
Login username case sensitivity

### ISSUE THREAD

**Issue by nelsonblaha** [cdubz/babybuddy#98]
In my opinion in this application's use case usernames should not be case-sensitive. My wife just now had quite a struggle with her phone's autocorrect capitalizing her name. She couldn't figure out it was case-sensitive.

**Comment by cdubz** [comment]
I would be tough sell on removing case sensitivity, but there are a number of HTML attributes that could be useful to turn off for that field --

- [`autocapitalize`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize)
- [`spellcheck`](https://html.spec.whatwg.org/multipage/interaction.html#spelling-and-grammar-checking)
- [`autocomplete`](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill) (although this one may be more useful than not)
- [`autocorrect`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-autocorrect) (ditto above)

**Comment by nelsonblaha** [comment]
Looks like autocapitalize is already "none" as it should be, so I'm going to blame my wife's phone for not cooperating on this one.

**Comment by cdubz** [comment]
Ah, I didn’t even check. Though I swear I have actually seen it autocapitalize before as well...

**Comment by nelsonblaha** [comment]
I think her phone's keyboard (LineageOS, Firefox) suggested her capitalized name despite the HTML.

**Comment by cdubz** [comment]
Ah. That is probably exactly where I saw the issue. We also have an older phone on Lineage.
